export type TextAlignType = 'center' | 'right' | 'left' | 'justify' | 'end' | 'start'
export type JustifyContentType = 'flex-start' | 'flex-end' | 'center' | 'space-around' | 'space-between'
export type AlignItemsType = 'stretch' | 'center' | 'flex-end' | 'flex-start' | 'baseline'
export type FlexWrapType = 'nowrap' | 'wrap' | 'wrap-reverse'
export type TextVariantsType = 'p' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
export type TextSizeType =
  | 'display-1'
  | 'display-2'
  | 'display-3'
  | 'display-4'
  | 'display-5'
  | 'display-6'
  | 'default'
  | 'small'
  | 'xsmall'
export type AppearanceOptions = 'main' | 'light' | 'darken'
export type IconPrefixType = 'fab' | 'fas'
export type IconNameType = 'trello' | 'chart-bar'
